[14.0][ADD] hr_timesheet_activity_begin_end_readonly_duration
solvosci/slv-timesheet pull request #13
Opened 2023-03-15 10:07 UTC by ChristianSantamaria

Change the readonly attribute of field unit_amount to true, to force the Begin Hour and End Hour to be added

2023-03-15 12:17 UTC, dalonsod requested changes
Only code review, see comments

2023-03-15 12:17 UTC, dalonsod commented on hr_timesheet_activity_begin_end_readonly_duration/models/analytic_account.py
> +    unit_amount = fields.Float(string="Quantity", default=0.0, readonly=True)
If only `readonly` has changed, only this code addition should be needed:
```suggestion
    unit_amount = fields.Float(readonly=True)
```

2023-03-15 12:17 UTC, dalonsod commented on hr_timesheet_activity_begin_end_readonly_duration/models/analytic_account.py
> +            line.unit_amount = (stop - start).seconds / 3600
Why is this code needed? If it's finally required, better try this (code reuse, from https://github.com/OCA/timesheet/blob/14.0/hr_timesheet_activity_begin_end/models/account_analytic_line.py#L72):
```suggestion
            line.onchange_hours_start_stop()
```

2023-03-15 12:17 UTC, dalonsod commented on hr_timesheet_activity_begin_end_readonly_duration/__manifest__.py
> +    "license": "LGPL-3",
This module depends on an OCA addon, so we should this license instead
```suggestion
    "license": "AGPL-3",
```

2023-03-15 13:37 UTC, ChristianSantamaria commented
Done 👍

2023-03-15 14:48 UTC, dalonsod commented
OK, I'll test it ASAP!

2023-03-15 15:26 UTC, dalonsod commented
Locally tested, 👍 

There's only a minor problem in form view edition (you can reach it using kanban view): `hr_timesheet_activity_begin_end` doesn't provide `time_start` and `time_stop` fields here. Then, we're unable to set timesheet hours.

So, I've temporary added them (this sould be a later contribution to OCA IMO).

@ChristianSantamaria could you install it in ArvTest environment?

2023-03-16 08:56 UTC, ChristianSantamaria commented
Instaled and tested in test enviroment, LGTM 👍

2023-03-16 09:05 UTC, dalonsod commented
Great!
I think the two separate commits should be kept in this situation, so no squash needed. You can follow the OCA proposed patch here: OCA/timesheet#577

2023-03-16 11:48 UTC, merged