[ADD] hr_timesheet_hours_month: Adds 2 fields that calculate monthly …
solvosci/slv-timesheet pull request #17
Opened 2024-01-12 07:41 UTC by Anxo82

Adds 2 fields that calculate monthly hours of a project.

2024-01-12 07:57 UTC, ChristianSantamaria commented
Some improvements:
- Name commits that are ADD do not need a description, that is, they should be "[ADD] hr_timesheet_hours_month"
- Don't forget to add the translations template too (.pot)

2024-01-12 10:03 UTC, dalonsod requested changes
Not tested yet, see comments

2024-01-12 10:03 UTC, dalonsod commented on hr_timesheet_hours_month/models/project_task.py
> +            record.remaining_hours_month = record.remaining_hours - (record.planned_hours - (n_month * (record.planned_hours / 12)))
This calculation should contain an `if` `else` statement, because if `planned_hours_year` is `False`, its value is automatically `0.0`.

2024-01-12 10:03 UTC, dalonsod commented on hr_timesheet_hours_month/views/project_task_view.xml
> +                <field name="remaining_hours_month" string="Remaining hours month" attrs="{'invisible': [('planned_hours_year','=',False)]}"/>
Use proper widget that formats this value to `hh:mm`, as other float time fields.

2024-01-12 10:03 UTC, dalonsod commented on hr_timesheet_hours_month/views/project_task_view.xml
> +                <field name="planned_hours_year" string="Planned hours to year"/>
Add a boolean toggle widget, like this: 

https://github.com/solvosci/slv-field-service/blob/c1a049340b346bc658c001192e5769a4af69334d/fieldservice_person_salary/views/fsm_order_salary_views.xml#L38

2024-01-12 11:51 UTC, dalonsod requested changes
Locally tested :+1: See comments, and also:
- Add to task `search` view a filter for those tasks with `planned_hours_year` set to `True`.

2024-01-12 11:51 UTC, dalonsod commented on hr_timesheet_hours_month/views/project_task_view.xml
> +                <field name="remaining_hours_month" widget="float_time" string="Remaining hours month" attrs="{'invisible': [('planned_hours_year','=',False)]}"/>
This field could be better placed at the bottom of the notebook page, with total remaining hours

2024-01-12 11:51 UTC, dalonsod commented on hr_timesheet_hours_month/models/project_task.py
> +    remaining_hours_month = fields.Float(compute='_compute_remaining_hours_month')
This field should be `compute_sudo=True` (see https://www.odoo.com/documentation/15.0/developer/reference/backend/orm.html#fields), as is non-stored. Users that can't access other users' timesheets can't properly calculate if not.

2024-01-16 18:21 UTC, dalonsod requested changes
See comment, when done I'll test it

2024-01-16 18:21 UTC, dalonsod commented on hr_timesheet_hours_month/models/project_task.py
> +        name_mapping = dict(super().name_get())
In parent code (in `hr_timesheet`) remaining hours text is only added when these conditions are met:
- `hr_timesheet_display_remaining_hours` is provided by context.
- task is allowed for timesheets, and
- planned hours are positive.

Only the last one is covered, we should add the other restrictions.

2024-01-17 08:25 UTC, dalonsod requested changes
Looks good... I'll test it once last comment is attended

2024-01-17 08:25 UTC, dalonsod commented on hr_timesheet_hours_month/models/project_task.py
> +            for task in self:
Try to use `filtered` instead `for` followed by an `if`.

2024-01-17 09:31 UTC, dalonsod commented
@ChristianSantamaria @Anxo82 could you check if PR is up to date with `15.0` or a rebase is required?

2024-01-17 15:26 UTC, Anxo82 commented
@dalonsod Done 👍

2024-01-17 15:33 UTC, dalonsod commented
OK,

@ChristianSantamaria could you install it in nk-test database?

2024-01-17 16:19 UTC, ChristianSantamaria commented
@dalonsod Done 👍 x2

2024-03-30 10:51 UTC, dalonsod approved these changes

2024-03-30 10:51 UTC, merged