[12.0][ADD] hr_timesheet_report_not_valued
solvosci/slv-timesheet pull request #2
Opened 2021-06-11 12:50 UTC by ChristianSantamaria

Adds a report that hides the time field.

2021-06-13 10:42 UTC, dalonsod requested changes
See initial comments.

I propose a different approach: modifying current report without creating another one, and use parameters in order to apply changes, when report is called. I don't really know if it's possible, but I'd try it.

2021-06-13 10:42 UTC, dalonsod commented on hr_timesheet_report_not_valued/__manifest__.py
> +        "helpdesk_mgmt",
The scope of this change shouldn't depend on this addon

2021-06-13 10:42 UTC, dalonsod commented on hr_timesheet_report_not_valued/__manifest__.py
> +    "category": "After-Sales",
Better this:
```suggestion
    "category": "Human Resources",
```

2021-06-14 11:23 UTC, dalonsod approved these changes
Tested standalone and interacting with other addons that also alters the same report (`helpdesk_mgmt_timesheet`, `helpdesk_mgmt_timesheet_ticket_name`,...)

2021-06-14 11:23 UTC, dalonsod commented on hr_timesheet_report_not_valued/i18n/es.po
> +msgstr "Detalle de los partes de horas no valoradas"
Better this:
```suggestion
msgstr "Detalle de los partes de horas no valorado"
```

2021-06-14 11:25 UTC, dalonsod commented
@lmiguens-solvos could you check?

2021-06-15 15:21 UTC, lmiguens-solvos approved these changes
LGTM

2021-06-16 16:35 UTC, dalonsod requested changes
Missing `README` files and one comment on `manifest` file. When done, I'll merge it

2021-06-16 16:35 UTC, dalonsod commented on hr_timesheet_report_not_valued/__manifest__.py
> +    "website": "https://github.com/solvosci/slv-helpdesk",
Typo in manifest

```suggestion
    "website": "https://github.com/solvosci/slv-timesheet",
```

2021-06-28 07:59 UTC, merged