[15.0][ADD] Module to add weekday filter
solvosci/slv-timesheet pull request #7
Opened 2022-12-05 10:31 UTC by adriresu

2022-12-05 10:50 UTC, dalonsod requested changes
Only code review, see comments. Only cosmetic fixes or changes required, code looks to be good.

BTW, commit message should be "[ADD] hr_timesheet_day_week"

And, at last, why LICENSE and README.md root files are deleted?

2022-12-05 10:50 UTC, dalonsod commented on hr_timesheet_day_week/__manifest__.py
> +    "name": "Add Weekdays to time sheets",
Better this:
```suggestion
    "name": "Add day of week management to timesheets",
```
* 'Weekday' is different than 'day of week' AFAIK. 'Weekday' only refers to a day that is used to go work.
* 'Time sheet' is ambiguous, better official 'timesheet'.

2022-12-05 10:50 UTC, dalonsod commented on hr_timesheet_day_week/__manifest__.py
> +    "license": "AGPL-3",
Use LGPL by default, if no OCA module involved:
```suggestion
    "license": "LGPL-3",
```

2022-12-05 10:50 UTC, dalonsod commented on hr_timesheet_day_week/models/account_analytic_line.py
> +        ("3", "Thurday"),
Typos:
```suggestion
        ("1", "Tuesday"),
        ("2", "Wednesday"),
        ("3", "Thursday"),
```

2022-12-05 10:50 UTC, dalonsod commented on hr_timesheet_day_week/models/account_analytic_line.py
> +    days_week = fields.Selection([
IMO this is a better name:
```suggestion
    day_week = fields.Selection([
```

2022-12-05 11:41 UTC, adriresu commented on hr_timesheet_day_week/models/account_analytic_line.py
> +        ("3", "Thurday"),
Updated mentioned changes

2022-12-05 11:51 UTC, dalonsod commented
Thanks, I'll test it ASAP

2022-12-05 13:20 UTC, dalonsod approved these changes
Locally tested, 👍 

Please only attend the later comments for cleaning code and encoding typos, and I'll merge it

2022-12-05 13:20 UTC, dalonsod commented on hr_timesheet_day_week/README.rst
> +* Solvos ConsultorÃ­a InformÃ¡tica
Please manually fix encoding typo

2022-12-05 13:20 UTC, dalonsod commented on hr_timesheet_day_week/static/description/index.html
> +<li>Solvos ConsultorÃƒÂ­a InformÃƒÂ¡tica</li>
Please manually fix encoding typo

2022-12-05 13:20 UTC, dalonsod commented on hr_timesheet_day_week/static/description/index.html
> +<li>AdriÃ¡n ResÃºa &lt;<a class="reference external" href="mailto:adrian.resua&#64;solvos.es">adrian.resua&#64;solvos.es</a>&gt;</li>
Please manually fix encoding typo

2022-12-05 13:20 UTC, dalonsod commented on hr_timesheet_day_week/views/hr_timesheet_view.xml
> +                <filter name="day_week" string="Weekend" domain="['|', ('day_week','=','5'), ('day_week','=','6')]"/>
Cleaner code IMO:
```suggestion
                <filter name="day_week" string="Weekend" domain="[('day_week','in', ['5', '6'])]"/>
```

2022-12-05 13:20 UTC, dalonsod commented on hr_timesheet_day_week/views/hr_timesheet_view.xml
> +                <attribute name="decoration-warning">day_week == '5' or day_week == '6'</attribute>
Cleaner code:
```suggestion
                <attribute name="decoration-warning">day_week in ['5', '6']</attribute>
```

2022-12-23 15:40 UTC, dalonsod commented
Made some minor changes:

- Category in manifest.
- Weekend domain condition in views moved from `or` clauses to `in` clause.
- Some encoding typos in `README` and `index.html` files.

2022-12-23 15:40 UTC, merged