[15.0][ADD] hr_timesheet_menu_filters
solvosci/slv-timesheet pull request #9
Opened 2023-01-03 09:49 UTC by adriresu

Adds new filters to timesheet view.
I also added "this week" as default filter view, passing it by context.
Review it ASAP :[)

2023-01-03 13:17 UTC, dalonsod requested changes
Only code review, see comments.

2023-01-03 13:17 UTC, dalonsod commented on hr_timesheet_menu_filters/views/hr_timesheet_view.xml
> +        <field name="context">{'search_default_this_week':1}</field>
Please look at original Odoo code:

https://github.com/odoo/odoo/blob/15.0/addons/hr_timesheet/views/hr_timesheet_views.xml#L258

- `search_view_id` is already filled, IMO this line should be removed.
- `hr_timesheet` module already has a `search_default_week` context value. How does it work?

2023-01-03 13:17 UTC, dalonsod commented on hr_timesheet_menu_filters/models/account_analytic_line.py
> +    _inherit = "account.analytic.line"
Is this file really needed?

2023-01-03 13:17 UTC, dalonsod commented on hr_timesheet_menu_filters/__manifest__.py
> +# © 2022 Solvos Consultoría Informática (<http://www.solvos.es>)
Wrong year:
```suggestion
# © 2023 Solvos Consultoría Informática (<http://www.solvos.es>)
```

2023-01-05 17:58 UTC, dalonsod commented
See changes:
- Minor change in `es` translation.
- Added `<separator/>` between Day and Week based filters, because e.g. "today or this week" filter has no sense IMO.
- Simplified date expressions (removed `datetime.combine` and `hh:mm:ss` use).

Could you test? If it's everything fine, please squash commits and do `README` stuff.

One last thing: your commit emai is weird (`Author: resua <32322359+adriresu@users.noreply.github.com>`). Could you check? Thanks!

2023-01-09 07:30 UTC, adriresu reviewed
Looks good

2023-01-10 09:24 UTC, dalonsod approved these changes
LGTM

2023-01-10 09:24 UTC, merged